-- Write your query below
SELECT TEAM_ID, TEAM_NAME, COALESCE(HOMEPOINTS, 0) + COALESCE(GUESTPOINTS, 0) AS NUM_POINTS
FROM TEAMS
LEFT JOIN (
    SELECT HOST_TEAM AS TEAM_ID,
    SUM(CASE
        WHEN HOST_GOALS > GUEST_GOALS THEN 3
        WHEN HOST_GOALS = GUEST_GOALS THEN 1
        ELSE 0
    END) AS HOMEPOINTS
    FROM MATCHES
    GROUP BY HOST_TEAM
) USING (TEAM_ID)
LEFT JOIN (
    SELECT GUEST_TEAM AS TEAM_ID,
    SUM(CASE
        WHEN GUEST_GOALS > HOST_GOALS THEN 3
        WHEN GUEST_GOALS = HOST_GOALS THEN 1
        ELSE 0
    END) AS GUESTPOINTS
    FROM MATCHES
    GROUP BY GUEST_TEAM
) USING (TEAM_ID)
ORDER BY NUM_POINTS DESC, TEAM_ID;