-- Write your query below
SELECT T.TEAM_ID, T.TEAM_NAME,
COALESCE(SUM(
    CASE
        WHEN T.TEAM_ID = M.HOST_TEAM AND M.HOST_GOALS > M.GUEST_GOALS THEN 3
        WHEN T.TEAM_ID = M.GUEST_TEAM AND M.GUEST_GOALS > M.HOST_GOALS THEN 3
        WHEN M.HOST_GOALS = M.GUEST_GOALS THEN 1
        ELSE 0
    END
), 0) AS NUM_POINTS
FROM TEAMS T
LEFT JOIN MATCHES M ON T.TEAM_ID = M.HOST_TEAM OR T.TEAM_ID = M.GUEST_TEAM
GROUP BY T.TEAM_ID, T.TEAM_NAME
ORDER BY NUM_POINTS DESC, T.TEAM_ID;