-- Write your query below
SELECT
    CASE WHEN FROM_ID < TO_ID THEN FROM_ID ELSE TO_ID END AS PERSON1,
    CASE WHEN FROM_ID < TO_ID THEN TO_ID ELSE FROM_ID END AS PERSON2,
    COUNT(*) AS CALL_COUNT,
    SUM(DURATION) AS TOTAL_DURATION
FROM CALLS
GROUP BY PERSON1, PERSON2;