-- Write your query below
SELECT U.NAME, COALESCE(SUM(R.DISTANCE), 0) AS TRAVELLED_DISTANCE
FROM USERS U
LEFT JOIN RIDES R ON R.USER_ID = U.ID
GROUP BY U.NAME
ORDER BY TRAVELLED_DISTANCE DESC, U.NAME;