-- Write your query below
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME
FROM CUSTOMERS
JOIN ORDERS USING (CUSTOMER_ID)
WHERE CUSTOMER_ID IN (
    SELECT DISTINCT CUSTOMER_ID  
    FROM CUSTOMERS
    JOIN ORDERS USING (CUSTOMER_ID)
    WHERE PRODUCT_NAME IN ('A')
) AND CUSTOMER_ID IN(
    SELECT DISTINCT CUSTOMER_ID  
    FROM CUSTOMERS
    JOIN ORDERS USING (CUSTOMER_ID)
    WHERE PRODUCT_NAME IN ('B')
) AND CUSTOMER_ID NOT IN (
    SELECT DISTINCT CUSTOMER_ID  
    FROM CUSTOMERS
    JOIN ORDERS USING (CUSTOMER_ID)
    WHERE PRODUCT_NAME IN ('C')
)
ORDER BY CUSTOMER_NAME
;