-- Write your query below
SELECT CUSTOMER_ID, CUSTOMER_NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID  
    FROM ORDERS
    WHERE PRODUCT_NAME = 'A'
) AND CUSTOMER_ID IN(
    SELECT CUSTOMER_ID  
    FROM ORDERS
    WHERE PRODUCT_NAME = 'B'
) AND CUSTOMER_ID NOT IN (
    SELECT CUSTOMER_ID  
    FROM ORDERS
    WHERE PRODUCT_NAME = 'C'
)
ORDER BY CUSTOMER_NAME
;