-- Write your query below
SELECT CUSTOMER_ID, CUSTOMER_NAME
FROM CUSTOMERS C
WHERE C.CUSTOMER_ID IN (
    SELECT CUSTOMER_ID FROM ORDERS WHERE PRODUCT_NAME = 'A'
) AND C.CUSTOMER_ID IN (
    SELECT CUSTOMER_ID FROM ORDERS WHERE PRODUCT_NAME = 'B'
) AND C.CUSTOMER_ID NOT IN (
    SELECT CUSTOMER_ID FROM ORDERS WHERE PRODUCT_NAME = 'C'
)
ORDER BY CUSTOMER_NAME;