-- Write your query below
SELECT CUSTOMER_ID, NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
    JOIN PRODUCT USING (PRODUCT_ID)
    WHERE TO_CHAR(ORDER_DATE::TIMESTAMP, 'YYYYMM') = '202006'
    GROUP BY CUSTOMER_ID
    HAVING SUM(QUANTITY * PRICE) >= 100
) AND CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM ORDERS
    JOIN PRODUCT USING (PRODUCT_ID)
    WHERE TO_CHAR(ORDER_DATE::TIMESTAMP, 'YYYYMM') = '202007'
    GROUP BY CUSTOMER_ID
    HAVING SUM(QUANTITY * PRICE) >= 100
)