-- Write your query below
SELECT C.NAME AS COUNTRY
FROM PERSON P
JOIN COUNTRY C ON SUBSTR(P.PHONE_NUMBER, 0, 4) = C.COUNTRY_CODE
JOIN CALLS CL ON P.ID = CL.CALLER_ID
GROUP BY C.NAME
HAVING AVG(CL.DURATION) > (
    SELECT AVG(DURATION)
    FROM CALLS
)
;