-- Write your query below
SELECT STUDENT_ID, MIN(EXAM_ID) EXAM_ID, SCORE
FROM EXAM_RESULTS E
WHERE SCORE = (SELECT MAX(SCORE) FROM EXAM_RESULTS WHERE E.STUDENT_ID = STUDENT_ID)
GROUP BY STUDENT_ID, SCORE
ORDER BY STUDENT_ID