-- Write your query below
SELECT E.LEFT_OPERAND, E.OPERATOR, E.RIGHT_OPERAND,
CASE
    WHEN E.OPERATOR = '>' AND LV.VALUE > RV.VALUE THEN 'true'
    WHEN E.OPERATOR = '<' AND LV.VALUE < RV.VALUE THEN 'true'
    WHEN E.OPERATOR = '=' AND LV.VALUE = RV.VALUE THEN 'true'
    ELSE 'false'
    END AS VALUE
FROM EXPRESSIONS E
JOIN VARIABLES LV ON E.LEFT_OPERAND = LV.NAME
JOIN VARIABLES RV ON E.RIGHT_OPERAND = RV.NAME