-- Write your query below
SELECT S.SELLER_NAME
FROM SELLER S
LEFT JOIN ORDERS O 
    ON S.SELLER_ID = O.SELLER_ID
    AND EXTRACT(YEAR FROM O.SALE_DATE) = 2020
WHERE O.ORDER_ID IS NULL
ORDER BY S.SELLER_NAME;