-- Write your query below
SELECT DISTINCT TITLE
FROM TV_PROGRAM
JOIN CONTENT USING (CONTENT_ID)
WHERE TO_CHAR(PROGRAM_DATE::TIMESTAMP, 'YYYYMM') = '202006'
    AND KIDS_CONTENT = 'Y'
    AND CONTENT_TYPE = 'Movies'