-- Write your query below

SELECT DISTINCT CUSTOMER_NUMBER
FROM ORDERS
LEFT JOIN (
    SELECT CUSTOMER_NUMBER, COUNT(*) COUNTS
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
    ORDER BY COUNT(*) DESC
) USING (CUSTOMER_NUMBER)
WHERE COUNTS = (
    SELECT COUNT(*) COUNTS
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 1
    )